[workspace]
members = [
    "qa_process",
    "templating_handlebars",
    "state_store_component",
    "packager",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1"
greentic-pack = ">=1.1.0-0, <1.2.0-0"
greentic-flow = ">=1.1.0-0, <1.2.0-0"
indexmap = "2"
semver = "1"
serde_json = "1"
serde_yaml_bw = { package = "serde_yaml_gtc", version = "2.5.2" }
wit-bindgen = "0.50"

[workspace.dependencies.clap]
version = "4"
features = [
    "derive",
]

[workspace.dependencies.serde]
version = "1"
features = [
    "derive",
]

[workspace.dependencies.time]
version = "0.3"
features = [
    "formatting",
]

[workspace.dependencies.zip]
version = "6"
default-features = false
features = [
    "deflate-flate2",
]

[workspace.dependencies.flate2]
version = "1.1"
default-features = false
features = [
    "rust_backend",
]
